[project]
name = "Flask-Pydantic"
version = "0.14.0"
description = "Flask extension for integration with Pydantic library."
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [{ name = "Jiri Bauer" }]
maintainers = [{ name = "Pallets", email = "contact@palletsprojects.com" }]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.7"
dependencies = [
    "Flask",
    "pydantic>=2.0",
    "typing_extensions>=4.1.1; python_version < '3.8'"
]

[project.urls]
Donate = "https://palletsprojects.com/donate"
Source = "https://github.com/pallets-eco/flask-pydantic"
Chat = "https://discord.gg/pallets"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "flask_pydantic"

[tool.pytest]
testpaths = ["tests"]
addopts = ["-vv", "--ruff", "--ruff-format", "--cov", "--cov-config=pyproject.toml", "-s"]

[tool.ruff]
src = ["flask_pydantic"]
lint.select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]
lint.ignore = ["E501"]

[tool.coverage.run]
branch = true
omit = [
    "example/*"
]
include = [
    "flask_pydantic/*"
]

[tool.coverage.report]
show_missing = true
skip_covered = true

[dependency-groups]
build = [
    "build>=1.1.1",
]
test = [
    "flask[async]>=2.2.5",
    "pytest>=7.4.4",
    "pytest-coverage>=0.0",
    "pytest-flask>=1.3.0",
    "pytest-mock>=3.11.1",
    "pytest-ruff>=0.2.1",
]
